import {useEffect,useMemo,useRef,useState} from 'react';
import type {ChangeEvent} from 'react';
import {BLOCKS,DAYS,initialData} from './data';
import {autoPlace,metrics,teacherRows,validateManual} from './scheduler';
import type {AppData,Assignment,Subject,Teacher,VersionSnapshot} from './types';

const KEY='girne-maarif-ders-atolyesi-v2';
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));
const csvEscape=(s:unknown)=>`"${String(s??'').replaceAll('"','""')}"`;
function download(name:string,content:string,type='text/plain;charset=utf-8'){const b=new Blob([content],{type});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function teacherName(data:AppData,id:string|null){return data.teachers.find(t=>t.id===id)?.name||(id?'Bilinmiyor':'Açık Kadro')}
function App(){
 const [data,setData]=useState<AppData>(()=>{try{const x=localStorage.getItem(KEY);return x?JSON.parse(x):initialData()}catch{return initialData()}});
 const [tab,setTab]=useState<'program'|'full'|'loads'|'quotas'|'teachers'|'settings'|'versions'>('program');
 const [fullFit,setFullFit]=useState(true);
 const [day,setDay]=useState(DAYS[0]); const [classFilter,setClassFilter]=useState('all'); const [teacherFilter,setTeacherFilter]=useState('all'); const [subjectFilter,setSubjectFilter]=useState('all');
 const [editing,setEditing]=useState<Assignment|null>(null); const [toast,setToast]=useState(''); const [history,setHistory]=useState<AppData[]>([]); const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(data))}catch{setToast('Tarayıcı depolama kotası doldu. JSON yedeği almanız önerilir.')}},[data]);
 const push=(next:AppData)=>{setHistory(h=>[...h.slice(-19),clone(data)]);setData(next)};
 const m=useMemo(()=>metrics(data),[data]); const rows=useMemo(()=>teacherRows(data),[data]);
 const classes=data.classes.filter(c=>classFilter==='all'||c.id===classFilter);
 const fullClassOrder=['Kaplumbağalar','Civcivler','Tavşanlar','Arılar','Uğurböcekleri','Papatyalar','Laleler','Kelebekler','Sincaplar','Balıklar'];
 const fullClasses=[...data.classes].sort((a,b)=>fullClassOrder.indexOf(a.name)-fullClassOrder.indexOf(b.name));
 const shortTeacher=(id:string|null)=>{const n=teacherName(data,id); if(n==='Açık Kadro')return 'AÇIK'; const parts=n.trim().split(/\s+/); return (parts[0]||n).toLocaleUpperCase('tr-TR');};
 const filteredAssignments=(cId:string)=>BLOCKS.map(b=>data.assignments.find(a=>a.classId===cId&&a.day===day&&a.blockId===b.id)).map(a=>a&&((teacherFilter==='all'||a.teacherId===teacherFilter)&&(subjectFilter==='all'||a.subjectId===subjectFilter)?a:null));
 const applyEdit=(a:Assignment)=>{const err=validateManual(data,a,a.teacherId);if(err){setToast(err);return}push({...data,assignments:data.assignments.map(x=>x.id===a.id?a:x)});setEditing(null);setToast('Ders kaydedildi.')};
 const doAuto=()=>{const r=autoPlace(data);push({...data,assignments:r.assignments});setToast(`Otomatik yerleştirme tamamlandı: ${r.placed} yerleştirme, ${r.unassigned} atanamayan.`)};
 const undo=()=>{const prev=history.at(-1);if(prev){setData(prev);setHistory(h=>h.slice(0,-1));setToast('Son değişiklik geri alındı.')}};
 const exportProgram=()=>{const head=['Gün','Sınıf','Ders','Saat','Öğretmen','Ders/Branş','Kilit','Not'];const lines=[head.map(csvEscape).join(';')];for(const a of data.assignments){const c=data.classes.find(x=>x.id===a.classId);const b=BLOCKS.find(x=>x.id===a.blockId);lines.push([a.day,c?.name,b?.label,`${b?.start}-${b?.end}`,teacherName(data,a.teacherId),a.title,a.locked?'Evet':'Hayır',a.note||''].map(csvEscape).join(';'))}download('girne-maarif-haftalik-program.csv','\uFEFF'+lines.join('\n'),'text/csv;charset=utf-8')};
 const exportLoads=()=>{const head=['Öğretmen','Statü','Hedef','Fiili',...DAYS,'Branş','Sınıf içi','Boş','Fark','Durum'];const lines=[head.map(csvEscape).join(';')];for(const r of rows)lines.push([r.t.name,r.t.status,r.t.weeklyTarget,r.total,...DAYS.map(d=>r.byDay[d]),r.branch,r.classroom,r.free,r.diff,r.status].map(csvEscape).join(';'));download('ogretmen-fiili-ders-yuku.csv','\uFEFF'+lines.join('\n'),'text/csv;charset=utf-8')};
 const saveVersion=()=>{const name=prompt('Sürüm adı:','Taslak '+(data.versions.length+1));if(!name)return;const v:VersionSnapshot={id:crypto.randomUUID(),name,createdAt:new Date().toISOString(),assignments:clone(data.assignments)};setData({...data,versions:[...data.versions,v]});setToast('Sürüm kaydedildi.')};
 const restoreVersion=(v:VersionSnapshot)=>{if(confirm(`${v.name} sürümüne dönülsün mü?`))push({...data,assignments:clone(v.assignments)})};
 const importJson=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{const parsed=JSON.parse(await f.text()) as AppData; if(!parsed.classes||!parsed.assignments)throw new Error();push(parsed);setToast('JSON yedeği yüklendi.')}catch{setToast('Geçersiz JSON yedeği.')}e.target.value=''};
 const addTeacher=()=>{const name=prompt('Öğretmen adı soyadı:');if(!name)return;const t:Teacher={id:crypto.randomUUID(),name,code:'Y'+(data.teachers.length+1),status:'Muvazzaf',subjectId:null,weeklyTarget:22,maxPerDay:6,unavailable:[],preferFree:[],active:true};push({...data,teachers:[...data.teachers,t]})};
 const addSubject=()=>{const name=prompt('Branş adı:');if(!name)return;const s:Subject={id:crypto.randomUUID(),name,code:name.slice(0,3).toUpperCase(),weeklyQuota:5,color:'#eef2f7'};push({...data,subjects:[...data.subjects,s]})};
 return <div className="app">
  <aside className="sidebar no-print"><div className="brand"><div className="logo">GM</div><div><strong>Ders Atölyesi</strong><small>Girne Maarif Anaokulu</small></div></div>
   <nav>{[['program','Haftalık Program'],['full','Tüm Program – Tek Sayfa'],['loads','Öğretmenler & Fiilî Yük'],['quotas','Branş Kotaları'],['teachers','Öğretmenler'],['settings','Ayarlar & Yedek'],['versions','Sürümler']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k as any)}>{l}</button>)}</nav>
   <div className="sidebar-note">Web uyumlu • Local-first • Google AI Studio’ya taşınabilir</div>
  </aside>
  <main className="main">
   <header className="top"><div><h1>{data.settings.schoolName} · DERS ATÖLYESİ</h1><p>{data.settings.year} Eğitim Öğretim Yılı</p></div><div className="actions no-print"><button onClick={undo} disabled={!history.length}>Geri Al</button><button onClick={doAuto}>Otomatik Yerleştir</button><button onClick={()=>window.print()}>Yazdır / PDF</button><button onClick={exportProgram}>CSV</button><button onClick={saveVersion}>Sürüm Kaydet</button></div></header>
   {toast&&<div className="toast" onClick={()=>setToast('')}>{toast}</div>}
   <section className="stats no-print"><div><b>{data.classes.length}</b><span>Sınıf / şube</span></div><div><b>{data.teachers.filter(t=>t.active).length}</b><span>Aktif öğretmen</span></div><div><b>{m.total}</b><span>Ders / hafta</span></div><div><b>{m.classroom} / {m.branch}</b><span>Sınıf / branş</span></div><div className={m.conflicts.length?'bad':'good'}><b>{m.conflicts.length}</b><span>Çakışma</span></div></section>
   {tab==='program'&&<>
    <div className="toolbar no-print"><div className="days">{DAYS.map(d=><button className={day===d?'sel':''} onClick={()=>setDay(d)} key={d}>{d}</button>)}</div><select value={classFilter} onChange={e=>setClassFilter(e.target.value)}><option value="all">Tüm sınıflar</option>{data.classes.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><select value={teacherFilter} onChange={e=>setTeacherFilter(e.target.value)}><option value="all">Tüm öğretmenler</option>{data.teachers.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select><select value={subjectFilter} onChange={e=>setSubjectFilter(e.target.value)}><option value="all">Tüm branşlar</option>{data.subjects.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></div>
    <div className="rulebar no-print"><span>🔒 Pazartesi 1. ders: {data.settings.protectMondayFirst?'Korumalı':'Kapalı'}</span><span>🛡️ 2. ve 6. ders: {data.settings.protectSecondAndSixth?'Korumalı':'Kapalı'}</span><span>Çakışma: {m.conflicts.length===0?'Yok':m.conflicts.length}</span></div>
    <div className="tablewrap"><table className="schedule"><thead><tr><th className="sticky">Sınıf / Sorumlu Öğretmen</th>{BLOCKS.map(b=><th key={b.id}>{b.label}<small>{b.start}–{b.end}</small></th>)}</tr></thead><tbody>{classes.map(c=>{const arr=filteredAssignments(c.id);return <tr key={c.id}><th className="sticky classcell"><strong>{c.name}</strong><small>{teacherName(data,c.teacherId)}</small></th>{arr.map((a,i)=>a?<td key={i} onClick={()=>setEditing(clone(a))} className={`${a.protected?'protected ':''}${a.vacancy?'vacancy':''}`} style={{background:a.subjectId?data.subjects.find(s=>s.id===a.subjectId)?.color:undefined}}><b>{a.title}</b><span>{teacherName(data,a.teacherId)}</span>{a.locked&&<em>🔒 Kilitli</em>}{a.reason&&<em>⚠ {a.reason}</em>}</td>:<td key={i} className="filtered">Filtre</td>)}</tr>})}</tbody></table></div>
   </>}
   {tab==='full'&&<section className={`full-program-panel ${fullFit?'fit':''}`}>
    <div className="full-program-tools no-print"><div><h2>Tüm Program – Tek Sayfa</h2><p>Gönderdiğiniz çizelge formuna göre Pazartesi–Cuma, 6 ders ve 10 sınıfın tamamı tek tabloda.</p></div><div><button className={fullFit?'primary':''} onClick={()=>setFullFit(v=>!v)}>{fullFit?'Sığdırma Açık':'Tek Sayfaya Sığdır'}</button><button onClick={()=>window.print()}>Bu Görünümü Yazdır / PDF</button></div></div>
    <div className="full-program-meta"><strong>{data.settings.schoolName}</strong><span>{data.settings.year} · HAFTALIK TÜM PROGRAM</span><span className="full-time-legend">{BLOCKS.map(b=>`${b.id}: ${b.start}–${b.end}`).join('  •  ')}</span></div>
    <div className="full-program-wrap"><table className="full-program-table"><thead><tr><th className="day-head">GÜN</th><th className="lesson-head">DERS</th>{fullClasses.map(c=><th key={c.id}>{c.name}</th>)}</tr></thead><tbody>{DAYS.map(d=>BLOCKS.map((b,bi)=><tr key={`${d}-${b.id}`} className={bi===0?'day-start':''}>{bi===0&&<th className="day-cell" rowSpan={BLOCKS.length}>{d.toLocaleUpperCase('tr-TR')}</th>}<th className="lesson-cell"><b>{b.id}</b><small>{b.start}<br/>{b.end}</small></th>{fullClasses.map(c=>{const a=data.assignments.find(x=>x.classId===c.id&&x.day===d&&x.blockId===b.id); const subj=a?.subjectId?data.subjects.find(s=>s.id===a.subjectId):null; const isBranch=!!a?.subjectId; const bg=a?.vacancy?'#f6c49c':(subj?.color||(a?.protected?'#f7f3e6':'#ffffff')); return <td key={c.id} className={`${a?.protected?'full-protected ':''}${a?.vacancy?'full-vacancy ':''}${isBranch?'full-branch':''}`} style={{background:bg}} title={a?`${a.title} — ${teacherName(data,a.teacherId)}`:'Boş'} onClick={()=>a&&setEditing(clone(a))}>{a?<><b className="full-teacher">{shortTeacher(a.teacherId)}</b><span className="full-title">{a.title}</span>{a.locked&&<em>🔒</em>}</>:<span className="full-empty">—</span>}</td>})}</tr>))}<tr className="class-teachers-row"><th colSpan={2}>SINIF ÖĞRETMENİ</th>{fullClasses.map(c=><td key={c.id}><b>{teacherName(data,c.teacherId)}</b></td>)}</tr></tbody></table></div>
    <div className="full-program-foot"><span>Renkli hücreler branş derslerini/korunan alanları gösterir.</span><span>Hücreye tıklayarak ders detayını düzenleyebilirsiniz.</span></div>
   </section>}
   {tab==='loads'&&<section className="panel"><div className="panelhead"><div><h2>Öğretmen Fiilî Ders Yükü Cetveli</h2><p>Programdaki her değişiklikten otomatik hesaplanır.</p></div><button className="no-print" onClick={exportLoads}>Fiilî Yük CSV</button></div><div className="tablewrap"><table><thead><tr><th>Öğretmen</th><th>Statü</th><th>Hedef</th><th>Fiilî</th>{DAYS.map(d=><th key={d}>{d.slice(0,3)}</th>)}<th>Branş</th><th>Sınıf içi</th><th>Boş</th><th>Fark</th><th>Durum</th></tr></thead><tbody>{rows.map(r=><tr key={r.t.id}><td><b>{r.t.name}</b><small>{r.t.code}</small></td><td>{r.t.status}</td><td>{r.t.weeklyTarget}</td><td><div className="progress"><i style={{width:`${Math.min(100,r.total/Math.max(1,r.t.weeklyTarget)*100)}%`}}/></div>{r.total}</td>{DAYS.map(d=><td key={d}>{r.byDay[d]}</td>)}<td>{r.branch}</td><td>{r.classroom}</td><td>{r.free}</td><td>{r.diff>0?'+':''}{r.diff}</td><td><span className={`badge ${r.status.toLowerCase()}`}>{r.status}</span></td></tr>)}</tbody></table></div></section>}
   {tab==='quotas'&&<section className="panel"><div className="panelhead"><div><h2>Branş Kotaları</h2><p>Haftalık hedef ile planlanan dersleri karşılaştırır.</p></div><button className="no-print" onClick={addSubject}>+ Branş</button></div><div className="cards">{data.subjects.map(s=>{const planned=data.assignments.filter(a=>a.subjectId===s.id).length;const ts=data.teachers.filter(t=>t.subjectId===s.id);return <article key={s.id}><h3>{s.name}</h3><div className="quota"><b>{planned}</b><span>/ {s.weeklyQuota} ders</span></div><div className="progress"><i style={{width:`${Math.min(100,planned/Math.max(1,s.weeklyQuota)*100)}%`}}/></div><p>{ts.length?ts.map(t=>t.name).join(', '):'Öğretmen tanımlı değil'}</p><small>Fark: {planned-s.weeklyQuota>0?'+':''}{planned-s.weeklyQuota}</small></article>})}</div></section>}
   {tab==='teachers'&&<section className="panel"><div className="panelhead"><div><h2>Öğretmen Kadrosu</h2><p>Sınıf ve branş öğretmenleri.</p></div><button onClick={addTeacher}>+ Öğretmen</button></div><div className="cards teachers">{data.teachers.map(t=><article key={t.id}><h3>{t.name}</h3><p>{t.status} · {t.code}</p><p>{t.subjectId?data.subjects.find(s=>s.id===t.subjectId)?.name:'Sınıf öğretmeni'}</p><small>Hedef {t.weeklyTarget} saat · Günlük en çok {t.maxPerDay}</small></article>)}</div></section>}
   {tab==='settings'&&<section className="panel settings"><h2>Ayarlar & Yedek</h2><label><span>Okul adı</span><input value={data.settings.schoolName} onChange={e=>setData({...data,settings:{...data.settings,schoolName:e.target.value}})}/></label><label><span>Dönem</span><input value={data.settings.year} onChange={e=>setData({...data,settings:{...data.settings,year:e.target.value}})}/></label><label className="check"><input type="checkbox" checked={data.settings.protectMondayFirst} onChange={e=>setData({...data,settings:{...data.settings,protectMondayFirst:e.target.checked}})}/> Pazartesi 1. ders kuralı aktif</label><label className="check"><input type="checkbox" checked={data.settings.protectSecondAndSixth} onChange={e=>setData({...data,settings:{...data.settings,protectSecondAndSixth:e.target.checked}})}/> 2. ve 6. ders koruması aktif</label><div className="backup"><button onClick={()=>download('girne-maarif-yedek.json',JSON.stringify(data,null,2),'application/json')}>JSON Yedek Al</button><button onClick={()=>fileRef.current?.click()}>JSON Yükle</button><input hidden ref={fileRef} type="file" accept="application/json" onChange={importJson}/><button className="danger" onClick={()=>{if(confirm('Tüm veriler başlangıç verisine dönecek. Emin misiniz?'))setData(initialData())}}>Başlangıca Dön</button></div><div className="info"><b>Google AI Studio uyumluluğu</b><p>Uygulama standart React + TypeScript + Vite kullanır. Temel işlevler API anahtarı veya Lovable servisi gerektirmez.</p></div></section>}
   {tab==='versions'&&<section className="panel"><div className="panelhead"><div><h2>Program Sürümleri</h2><p>Taslak ve onaylı programları saklayın.</p></div><button onClick={saveVersion}>+ Sürüm Kaydet</button></div>{!data.versions.length?<div className="empty">Henüz sürüm yok.</div>:<div className="versionlist">{[...data.versions].reverse().map(v=><div key={v.id}><div><b>{v.name}</b><small>{new Date(v.createdAt).toLocaleString('tr-TR')}</small></div><button onClick={()=>restoreVersion(v)}>Bu sürüme dön</button></div>)}</div>}</section>}
   <footer className="print-footer">Oluşturma: {new Date().toLocaleDateString('tr-TR')} · Girne Maarif Anaokulu {data.settings.year}</footer>
  </main>
  {editing&&<div className="modalback"><div className="modal"><h2>Ders Detayı</h2><p><b>{data.classes.find(c=>c.id===editing.classId)?.name}</b> · {editing.day} · {BLOCKS.find(b=>b.id===editing.blockId)?.label}</p><label>Ders / etkinlik<input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Branş<select value={editing.subjectId||''} onChange={e=>setEditing({...editing,subjectId:e.target.value||null})}><option value="">Sınıf içi ders</option>{data.subjects.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Öğretmen<select value={editing.teacherId||''} onChange={e=>setEditing({...editing,teacherId:e.target.value||null,vacancy:!e.target.value})}><option value="">Açık Kadro / Atanmamış</option>{data.teachers.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Not<textarea value={editing.note||''} onChange={e=>setEditing({...editing,note:e.target.value})}/></label><label className="check"><input type="checkbox" checked={editing.locked} disabled={editing.protected&&editing.day==='Pazartesi'&&editing.blockId==='1'} onChange={e=>setEditing({...editing,locked:e.target.checked})}/> Kilitle</label>{editing.protected&&<div className="warn">Bu saat okul kuralı kapsamında korunan zaman dilimidir.</div>}<div className="modalactions"><button onClick={()=>setEditing(null)}>Vazgeç</button><button className="primary" onClick={()=>applyEdit(editing)}>Kaydet</button></div></div></div>}
 </div>
}
export default App;
