import { BLOCKS, DAYS } from './data';
import type { AppData, Assignment, Teacher } from './types';
const slot=(d:string,b:string)=>`${d}|${b}`;
function loadOf(data:AppData, teacherId:string, assignments:Assignment[]){const own=assignments.filter(a=>a.teacherId===teacherId);return {total:own.length,byDay:Object.fromEntries(DAYS.map(d=>[d,own.filter(a=>a.day===d).length])),slots:new Set(own.map(a=>slot(a.day,a.blockId)))};}
function validTeacher(data:AppData,t:Teacher,a:Assignment,working:Assignment[]){if(!t.active)return 'Öğretmen pasif'; if(a.subjectId && t.subjectId!==a.subjectId)return 'Branş uyuşmuyor'; if(!a.subjectId && t.subjectId)return 'Bu hücre sınıf öğretmeni dersi'; const l=loadOf(data,t.id,working); if(t.unavailable.includes(slot(a.day,a.blockId)))return 'Öğretmen bu saatte uygun değil'; if(l.slots.has(slot(a.day,a.blockId)))return 'Aynı saatte başka sınıfta dersi var'; if((l.byDay[a.day]||0)>=t.maxPerDay)return 'Günlük ders limiti dolu'; return null;}
export function validateManual(data:AppData,a:Assignment,teacherId:string|null){if(a.protected&&a.locked)return 'Bu hücre korunan ve kilitli bir zaman dilimidir.'; if(!teacherId)return null; const t=data.teachers.find(x=>x.id===teacherId); if(!t)return 'Öğretmen bulunamadı'; return validTeacher(data,t,a,data.assignments.filter(x=>x.id!==a.id));}
export function autoPlace(data:AppData){const working=data.assignments.map(a=>({...a})); let placed=0; let unassigned=0; for(const a of working){if(a.locked)continue; if(!a.subjectId)continue; const current=data.teachers.find(t=>t.id===a.teacherId); if(current&&!validTeacher(data,current,a,working.filter(x=>x.id!==a.id))) continue; const candidates=data.teachers.filter(t=>t.subjectId===a.subjectId&&t.active).map(t=>({t,reason:validTeacher(data,t,a,working.filter(x=>x.id!==a.id)),load:loadOf(data,t.id,working).total})).filter(x=>!x.reason).sort((x,y)=>x.load-y.load||x.t.code.localeCompare(y.t.code)); if(candidates[0]){a.teacherId=candidates[0].t.id;a.vacancy=false;a.reason=undefined;placed++;}else{a.teacherId=null;a.vacancy=true;a.reason='Uygun branş öğretmeni bulunamadı';unassigned++;}}
 return {assignments:working,placed,unassigned};}
export function metrics(data:AppData){const conflicts:string[]=[]; const seen=new Map<string,Assignment>(); for(const a of data.assignments){if(!a.teacherId)continue;const k=`${a.teacherId}|${a.day}|${a.blockId}`; if(seen.has(k)) conflicts.push(`${a.day} ${a.blockId}. ders öğretmen çakışması`); else seen.set(k,a);} const assigned=data.assignments.filter(a=>a.teacherId).length; const branch=data.assignments.filter(a=>a.subjectId).length; return {total:data.assignments.length,assigned,branch,classroom:data.assignments.length-branch,conflicts};}
export function teacherRows(data:AppData){return data.teachers.map(t=>{const own=data.assignments.filter(a=>a.teacherId===t.id);const branch=own.filter(a=>a.subjectId).length;const byDay=Object.fromEntries(DAYS.map(d=>[d,own.filter(a=>a.day===d).length]));const diff=own.length-t.weeklyTarget; return {t,total:own.length,branch,classroom:own.length-branch,byDay,diff,status:diff===0?'Uygun':diff<0?'Eksik':'Fazla',free:DAYS.length*BLOCKS.length-own.length};});}
